# This is a basic workflow to help you get started with Actions

name: MCMK1 24/7 Server v1.16.5

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Configurate
        run: |
          cd .git
          echo '${{ secrets.GIT_CONFIG }}' > config
          git config core.excludesfile ~/.gitignore
          git config pull.rebase false
          cat config
      - name: Sync
        run: |
          git pull server master --allow-unrelated-histories --quiet
          ls
      - name: Install Dependencies
        run: |
          npm i express
          npm i body-parser
          npm i ngrok
      - name: Initate Server
        run: node index.js
        env: 
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
