# This is a basic workflow to help you get started with Actions

name: MCMK1 24/7 Server v1.16.5

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  repository_dispatch:
    types: [startup]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Setup Java JDK
        uses: actions/setup-java@v2.1.0
        with:
    # The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file
          java-version: 16
          distribution: adopt
    # Java distribution. See the list of supported distributions in README file
      - uses: actions/checkout@v2
      - name: Configurate
        run: |
          java -version
          cd .git
          echo '${{ secrets.GIT_CONFIG }}' > config
          git config core.excludesfile ~/.gitignore
          git config pull.rebase false
          git config receive.shallowUpdate true
          git config http.postBuffer 524288000
          git config --global protocol.version 2
          cat config
      - name: Sync
        run: |
          git pull server gnon --allow-unrelated-histories --depth=1
      - name: fetch
        run: |
          git fetch --unshallow
          ls
      - name: Install Dependencies
        run: |
          npm i express
          npm i body-parser
          npm i ngrok
          npm i os-utils
      - name: Initate Server
        run: node index.js
        env: 
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          DDNS_API_KEY: ${{ secrets.DDNS_API_KEY }}
          ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          CONFIG: ${{ secrets.GIT_CONFIG }}
